FROM python:3.12-slim

WORKDIR /short_location

COPY ./docker/api/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r /short_location/requirements.txt

COPY ./api api

CMD ["fastapi", "run", "./api/main.py", "--port", "80"]

